Added notebook to make plot of decadal trends and plot
ClimateIndicator/forcing-timeseries pull request #1
Opened 2023-04-30 09:22 UTC by piers-forster

This is the first time, i've done a pull request  - what fun :)

2023-05-01 12:46 UTC, chrisroadmap commented
It's only by chance I saw this - GitHub doesn't notify me when people make PRs! Will check this afternoon :)

2023-05-02 06:03 UTC, chrisroadmap requested changes
Hi Piers, very nice 👍 

The path to Tristram's data has changed, see the comment.

The other thing that's nice to do is commit clean notebooks. You can either:
1.  go to Kernel > Restart & Clear Output in jupyter before committing;
2. automatically clean notebooks precommit by activating your conda environment and running `nbstripout --install` from the terminal.

Once those two things are done I will merge. Thanks :)

2023-05-02 06:03 UTC, chrisroadmap commented on notebooks/Decadaltrends.ipynb
> +    "GWI_df = pd.read_csv('https://raw.githubusercontent.com/ClimateIndicator/anthropogenic-warming-assessment/master/global-warming-index/results/Walsh_GMST_timeseries_6048000.csv')\n",
Tristram has changed the folder structure and this path doesn't work now. 

This should: https://raw.githubusercontent.com/ClimateIndicator/anthropogenic-warming-assessment/master/results/Walsh_GMST_timeseries_6048000.csv

The same file is also in the data repo and that will not change if you used the tagged version, but the column headers are different
https://github.com/ClimateIndicator/data/blob/v2023.05.01/data/anthropogenic_warming/Walsh_GMST_timeseries_6048000.csv

2023-05-02 21:19 UTC, chrisroadmap commented
Oh, one other thing: add to the README under the reproduction instructions - I assume this comes last in the chain.

2023-05-03 14:34 UTC, piers-forster commented
After about half an hours effort of trying to work out WTF to do - i think. I've made these changes   - do i need to do anything to try and merge again?

2023-05-04 05:49 UTC, chrisroadmap approved these changes

2023-05-04 05:50 UTC, merged